Repository flatcar/portage-stable, pull requests merged in 2020-10, with the labels that each got.

#111 bump(sys-libs/libseccomp): sync with upstream
  sys-libs/libseccomp/Manifest
  sys-libs/libseccomp/libseccomp-2.4.0.ebuild
  sys-libs/libseccomp/libseccomp-2.5.0.ebuild
Labels: alpha

#113 sys-fs/cryptsetup: moving to coreos-overlay
  profiles/targets/systemd/package.use.mask
  sys-fs/cryptsetup/Manifest
  sys-fs/cryptsetup/cryptsetup-1.7.5.ebuild
  sys-fs/cryptsetup/cryptsetup-2.0.2.ebuild
  sys-fs/cryptsetup/cryptsetup-2.0.3.ebuild
  sys-fs/cryptsetup/files/1.6.7-dmcrypt.confd
  sys-fs/cryptsetup/files/1.6.7-dmcrypt.rc
  sys-fs/cryptsetup/files/setup-1.7.0.py
  sys-fs/cryptsetup/metadata.xml
Labels: lts

#116 app-arch/tar: Sync package with upstream
  app-arch/tar/Manifest
  app-arch/tar/files/tar-1.31-remove-erroneous-abort-call.patch
  app-arch/tar/tar-1.32.90.ebuild
  app-arch/tar/tar-1.32.ebuild
Labels: alpha

#117 Update json-c, libuv, libxml2, c-ares
  dev-libs/json-c/Manifest
  dev-libs/json-c/files/json-c-0.14-cmake-static-libs.patch
  dev-libs/json-c/files/json-c-0.14-object-limitation.patch
  dev-libs/json-c/files/json-c-0.14-security-fix.patch
  dev-libs/json-c/json-c-0.12.1.ebuild
  dev-libs/json-c/json-c-0.12.ebuild
  dev-libs/json-c/json-c-0.13.1-r1.ebuild
  dev-libs/json-c/json-c-0.13.ebuild
  dev-libs/json-c/json-c-0.14-r3.ebuild
  dev-libs/json-c/json-c-0.15.ebuild
  dev-libs/json-c/json-c-9999.ebuild
  dev-libs/json-c/metadata.xml
  dev-libs/libuv/Manifest
  dev-libs/libuv/libuv-1.39.0.ebuild
  dev-libs/libuv/libuv-1.40.0.ebuild
  dev-libs/libuv/libuv-9999.ebuild
  dev-libs/libuv/metadata.xml
  dev-libs/libxml2/Manifest
  dev-libs/libxml2/files/2.9.9-python3-unicode-errors.patch
  dev-libs/libxml2/files/libxml2-2.8.0_rc1-winnt.patch
  dev-libs/libxml2/files/libxml2-2.9.8-out-of-tree-test.patch
  dev-libs/libxml2/libxml2-2.9.10-r2.ebuild
  dev-libs/libxml2/libxml2-2.9.10-r3.ebuild
  dev-libs/libxml2/libxml2-2.9.9-r4.ebuild
  eclass/cmake-multilib.eclass
  net-dns/c-ares/Manifest
  net-dns/c-ares/c-ares-1.16.1.ebuild
  sys-fs/cryptsetup/Manifest
  sys-fs/cryptsetup/cryptsetup-2.3.2.ebuild
  sys-fs/cryptsetup/cryptsetup-2.3.3.ebuild
  sys-fs/cryptsetup/cryptsetup-2.3.4.ebuild
  sys-fs/cryptsetup/files/cryptsetup-2.0.4-fix-static-pwquality-build.patch
  sys-fs/cryptsetup/files/setup-1.7.0.py
  sys-fs/cryptsetup/metadata.xml
Labels: main
