Repository flatcar/portage-stable, pull requests merged in 2020-04, with the labels that each got.

#44 virtual: rename virtual/cargo to virtual/rust for alpha
  metadata/md5-cache/virtual/cargo-1.34.2
  metadata/md5-cache/virtual/cargo-1.35.0
  metadata/md5-cache/virtual/cargo-1.36.0
  metadata/md5-cache/virtual/rust-1.41.1
  virtual/cargo/cargo-1.36.0.ebuild
  virtual/rust/metadata.xml
  virtual/rust/rust-1.41.1.ebuild
Labels: alpha

#45 virtual: rename virtual/cargo to virtual/rust for edge
  metadata/md5-cache/virtual/cargo-1.34.2
  metadata/md5-cache/virtual/cargo-1.35.0
  metadata/md5-cache/virtual/cargo-1.36.0
  metadata/md5-cache/virtual/cargo-1.37.0
  metadata/md5-cache/virtual/rust-1.41.1
  virtual/cargo/cargo-1.37.0.ebuild
  virtual/rust/metadata.xml
  virtual/rust/rust-1.41.1.ebuild
Labels: edge

#48 net-firewall/conntrack-tools: Add new package for kubeadm
  metadata/md5-cache/net-firewall/conntrack-tools-1.4.5
  metadata/md5-cache/net-firewall/conntrack-tools-1.4.6
  metadata/md5-cache/net-libs/libnetfilter_conntrack-1.0.6
  metadata/md5-cache/net-libs/libnetfilter_conntrack-1.0.7
  metadata/md5-cache/net-libs/libnetfilter_conntrack-1.0.8
  metadata/md5-cache/net-libs/libnetfilter_cthelper-1.0.0
  metadata/md5-cache/net-libs/libnetfilter_cthelper-1.0.0-r1
  metadata/md5-cache/net-libs/libnetfilter_cttimeout-1.0.0
  metadata/md5-cache/net-libs/libnetfilter_cttimeout-1.0.0-r1
  metadata/md5-cache/net-libs/libnetfilter_queue-1.0.2
  metadata/md5-cache/net-libs/libnetfilter_queue-1.0.3
  metadata/md5-cache/net-libs/libnfnetlink-1.0.1
  metadata/md5-cache/net-libs/rpcsvc-proto-0
  metadata/md5-cache/net-libs/rpcsvc-proto-1.3.1-r1
  metadata/md5-cache/net-libs/rpcsvc-proto-1.4
  metadata/md5-cache/sys-libs/talloc-2.1.5
  metadata/md5-cache/sys-libs/talloc-2.1.5-r1
  metadata/md5-cache/sys-libs/talloc-2.1.6
  metadata/md5-cache/sys-libs/tdb-1.3.8
  metadata/md5-cache/sys-libs/tevent-0.9.26
  metadata/md5-cache/sys-libs/tevent-0.9.27
  metadata/md5-cache/sys-libs/tevent-0.9.28
  net-firewall/conntrack-tools/Manifest
  net-firewall/conntrack-tools/conntrack-tools-1.4.5.ebuild
  net-firewall/conntrack-tools/conntrack-tools-1.4.6.ebuild
  net-firewall/conntrack-tools/files/conntrack-tools-1.4.5-rpc.patch
  net-firewall/conntrack-tools/files/conntrackd.confd-r2
  net-firewall/conntrack-tools/files/conntrackd.initd-r3
  net-firewall/conntrack-tools/metadata.xml
  net-libs/libnetfilter_conntrack/Manifest
  net-libs/libnetfilter_conntrack/libnetfilter_conntrack-1.0.6.ebuild
  net-libs/libnetfilter_conntrack/libnetfilter_conntrack-1.0.7.ebuild
  net-libs/libnetfilter_conntrack/libnetfilter_conntrack-1.0.8.ebuild
  net-libs/libnetfilter_conntrack/metadata.xml
  net-libs/libnetfilter_cthelper/Manifest
  net-libs/libnetfilter_cthelper/files/libnetfilter_cthelper-1.0.0-clang-export.patch
  net-libs/libnetfilter_cthelper/libnetfilter_cthelper-1.0.0-r1.ebuild
  net-libs/libnetfilter_cthelper/libnetfilter_cthelper-1.0.0.ebuild
  net-libs/libnetfilter_cthelper/metadata.xml
  net-libs/libnetfilter_cttimeout/Manifest
  net-libs/libnetfilter_cttimeout/files/libnetfilter_cttimeout-1.0.0-clang-export.patch
  net-libs/libnetfilter_cttimeout/libnetfilter_cttimeout-1.0.0-r1.ebuild
  net-libs/libnetfilter_cttimeout/libnetfilter_cttimeout-1.0.0.ebuild
  net-libs/libnetfilter_cttimeout/metadata.xml
  net-libs/libnetfilter_queue/Manifest
  net-libs/libnetfilter_queue/libnetfilter_queue-1.0.2.ebuild
  net-libs/libnetfilter_queue/libnetfilter_queue-1.0.3.ebuild
  net-libs/libnetfilter_queue/metadata.xml
  net-libs/libnfnetlink/Manifest
  net-libs/libnfnetlink/libnfnetlink-1.0.1.ebuild
  net-libs/libnfnetlink/metadata.xml
Labels: alpha, beta, edge, stable

#54 sys-devel/gdb: move gdb to coreos-overlay for edge
  metadata/md5-cache/sys-devel/gdb-8.3.1
  metadata/md5-cache/sys-devel/gdb-8.3.1-r1
  metadata/md5-cache/sys-devel/gdb-9.1
  metadata/md5-cache/sys-devel/gdb-9999
  sys-devel/gdb/Manifest
  sys-devel/gdb/files/gdb-8.3.1-gcc-10.patch
  sys-devel/gdb/files/gdb-8.3.1-verbose-build.patch
  sys-devel/gdb/gdb-8.3.1-r1.ebuild
  sys-devel/gdb/gdb-8.3.1.ebuild
  sys-devel/gdb/gdb-9.1.ebuild
  sys-devel/gdb/gdb-9999.ebuild
  sys-devel/gdb/metadata.xml
Labels: edge

#53 sys-devel/gdb: move gdb to coreos-overlay for alpha
  metadata/md5-cache/sys-devel/gdb-8.3.1
  metadata/md5-cache/sys-devel/gdb-8.3.1-r1
  metadata/md5-cache/sys-devel/gdb-9.1
  metadata/md5-cache/sys-devel/gdb-9999
  sys-devel/gdb/Manifest
  sys-devel/gdb/files/gdb-8.3.1-gcc-10.patch
  sys-devel/gdb/files/gdb-8.3.1-verbose-build.patch
  sys-devel/gdb/gdb-8.3.1-r1.ebuild
  sys-devel/gdb/gdb-8.3.1.ebuild
  sys-devel/gdb/gdb-9.1.ebuild
  sys-devel/gdb/gdb-9999.ebuild
  sys-devel/gdb/metadata.xml
Labels: alpha

#57 eclass: make cargo depend on virtual/rust for alpha
  eclass/cargo.eclass
  virtual/rust/rust-1.36.0.ebuild
Labels: alpha, bug

#58 eclass: make cargo depend on virtual/rust for edge
  eclass/cargo.eclass
  virtual/rust/rust-1.37.0.ebuild
Labels: bug, edge

#61 dev-lang/rust: remove duplicates, move to coreos-overlay
  dev-lang/rust/Manifest
  dev-lang/rust/files/0001-llvm-cmake-Add-additional-headers-only-if-they-exist.patch
  dev-lang/rust/files/1.34.0-doc-build-fix.patch
  dev-lang/rust/files/1.34.0-libressl.patch
  dev-lang/rust/files/1.34.2-fix-custom-libdir.patch
  dev-lang/rust/files/1.35.0-revert-commits-triggering-multiple-llvm-rebuilds.patch
  dev-lang/rust/files/1.36.0-libressl.patch
  dev-lang/rust/metadata.xml
  dev-lang/rust/rust-1.34.2.ebuild
  dev-lang/rust/rust-1.35.0.ebuild
  dev-lang/rust/rust-1.36.0.ebuild
Labels: alpha, beta, edge, stable
