Repository flatcar/portage-stable, pull requests merged in 2020-11, with the labels that each got.

#115 Update the glib package and the related dependencies
  dev-libs/glib/Manifest
  dev-libs/glib/files/glib-2.58.2-external-gdbus-codegen.patch
  dev-libs/glib/files/glib-2.64.1-mark-gdbus-server-auth-test-flaky.patch
  dev-libs/glib/glib-2.58.3.ebuild
  dev-libs/glib/glib-2.62.6.ebuild
  dev-libs/glib/glib-2.64.4.ebuild
  dev-libs/glib/glib-2.64.5.ebuild
  dev-util/glib-utils/Manifest
  dev-util/glib-utils/glib-utils-2.62.6.ebuild
  dev-util/glib-utils/glib-utils-2.64.4.ebuild
  dev-util/glib-utils/glib-utils-2.64.5.ebuild
Labels: alpha

#123 sys-block/open-isns: Add the new package
  sys-block/open-isns/Manifest
  sys-block/open-isns/files/open-isns-0.100-no_Werror.patch
  sys-block/open-isns/files/open-isns-0.98-libressl-compatibility.patch
  sys-block/open-isns/metadata.xml
  sys-block/open-isns/open-isns-0.100.ebuild
  sys-block/open-isns/open-isns-0.98.ebuild
  sys-block/open-isns/open-isns-0.99.ebuild
Labels: alpha

#126 dev-util/dwarves: introduce new dev tool dwarves
  dev-util/dwarves/Manifest
  dev-util/dwarves/dwarves-1.13.ebuild
  dev-util/dwarves/dwarves-1.15.ebuild
  dev-util/dwarves/dwarves-1.16-r1.ebuild
  dev-util/dwarves/dwarves-1.16.ebuild
  dev-util/dwarves/dwarves-1.17-r1.ebuild
  dev-util/dwarves/dwarves-1.17.ebuild
  dev-util/dwarves/dwarves-1.18.ebuild
  dev-util/dwarves/files/dwarves-1.16-no-libebl.patch
Labels: alpha, main

#114 virtual: Upgrade Rust 1.46.0 to 1.47.0
  virtual/rust/rust-1.47.0.ebuild
Labels: main
