Repository flatcar/portage-stable, pull requests merged in 2020-05, with the labels that each got.

#65 virtual/resolvconf: Add a new package, dependency of wireguard-tools
  metadata/md5-cache/dev-lang/rust-1.34.2
  metadata/md5-cache/dev-lang/rust-1.35.0
  metadata/md5-cache/dev-lang/rust-1.36.0
  metadata/md5-cache/virtual/resolvconf-1
  metadata/md5-cache/virtual/rust-1.36.0
  virtual/resolvconf/metadata.xml
  virtual/resolvconf/resolvconf-1.ebuild
Labels: alpha

#72 dev-libs/libgcrypt: fix syntax errors due to merge conflicts for edge
  dev-libs/libgcrypt/libgcrypt-1.8.4.ebuild
  dev-libs/libgcrypt/libgcrypt-1.8.5.ebuild
Labels: bug, edge

#62 dev-util/strace: move strace to coreos-overlay for alpha
  dev-util/strace/ChangeLog
  dev-util/strace/Manifest
  dev-util/strace/metadata.xml
  dev-util/strace/strace-4.10.ebuild
  dev-util/strace/strace-4.9.ebuild
  dev-util/strace/strace-9999.ebuild
  metadata/md5-cache/dev-util/strace-4.10
  metadata/md5-cache/dev-util/strace-4.9
  metadata/md5-cache/dev-util/strace-9999
Labels: alpha

#63 dev-util/strace: move strace to coreos-overlay for edge
  dev-util/strace/ChangeLog
  dev-util/strace/Manifest
  dev-util/strace/metadata.xml
  dev-util/strace/strace-4.10.ebuild
  dev-util/strace/strace-4.9.ebuild
  dev-util/strace/strace-9999.ebuild
  metadata/md5-cache/dev-util/strace-4.10
  metadata/md5-cache/dev-util/strace-4.9
  metadata/md5-cache/dev-util/strace-9999
Labels: edge
