Repository flatcar/portage-stable, pull requests merged in 2021-02, with the labels that each got.

#142 net-dns/c-ares: update to 1.17.1
  net-dns/c-ares/Manifest
  net-dns/c-ares/c-ares-1.17.1.ebuild
  net-dns/c-ares/files/c-ares-1.12.0-remove-tests.patch
Labels: alpha, main

#146 net-nds/openldap: Sync with Gentoo upstream
  net-nds/openldap/Manifest
  net-nds/openldap/metadata.xml
  net-nds/openldap/openldap-2.4.57.ebuild
Labels: alpha

#149 net-misc/dhcpcd: delete dhcpcd
  net-misc/dhcpcd/Manifest
  net-misc/dhcpcd/dhcpcd-8.1.9.ebuild
  net-misc/dhcpcd/dhcpcd-9.3.4.ebuild
  net-misc/dhcpcd/dhcpcd-9.4.0.ebuild
  net-misc/dhcpcd/dhcpcd-9999.ebuild
  net-misc/dhcpcd/files/dhcpcd.initd
  net-misc/dhcpcd/files/dhcpcd.initd-r1
  net-misc/dhcpcd/files/dhcpcd.service
  net-misc/dhcpcd/files/dhcpcd.service-r1
  net-misc/dhcpcd/metadata.xml
Labels: alpha, enhancement
