Repository flatcar/portage-stable, pull requests merged in 2021-08, with the labels that each got.

#194 app-portage/portage-utils: update to 0.90
  app-portage/portage-utils/Manifest
  app-portage/portage-utils/portage-utils-0.90.1.ebuild
  app-portage/portage-utils/portage-utils-0.90.ebuild
  app-portage/portage-utils/portage-utils-0.92.ebuild
  app-portage/portage-utils/portage-utils-9999.ebuild
Labels: alpha, stable, beta, main

#161 dev-util/ccache: delete ccache completely
  dev-util/ccache/Manifest
  dev-util/ccache/ccache-3.2.4.ebuild
  dev-util/ccache/ccache-3.2.5.ebuild
  dev-util/ccache/ccache-3.2.7.ebuild
  dev-util/ccache/ccache-3.3.3.ebuild
  dev-util/ccache/files/ccache-3.1.10-size-on-disk.patch
  dev-util/ccache/files/ccache-3.3-size-on-disk.patch
  dev-util/ccache/files/ccache-config-3
  dev-util/ccache/metadata.xml
  profiles/info_pkgs
Labels: alpha, main

#196 Update tar to 1.34
  app-arch/tar/Manifest
  app-arch/tar/tar-1.32.90.ebuild
  app-arch/tar/tar-1.34.ebuild
Labels: alpha

#199 net-dns/dnsmasq: Bump to v2.85
  net-dns/dnsmasq/Manifest
  net-dns/dnsmasq/dnsmasq-2.83-r101.ebuild
  net-dns/dnsmasq/dnsmasq-2.85.ebuild
  net-dns/dnsmasq/files/dnsmasq-2.84-version-string.patch
Labels: alpha

#201 dev-util/strace: move to portage-stable, update to 5.12
  dev-util/strace/Manifest
  dev-util/strace/files/strace-5.11-static.patch
  dev-util/strace/metadata.xml
  dev-util/strace/strace-5.11.ebuild
  dev-util/strace/strace-5.12.ebuild
  dev-util/strace/strace-5.13.ebuild
  dev-util/strace/strace-9999.ebuild
Labels: alpha, main
