Repository flatcar/portage-stable, pull requests merged in 2023-01, with the labels that each got.

#402 dev-libs/libksba: update to 1.6.3
  changelog/security/2023-01-05-libksba-1.6.3.md
  changelog/updates/2023-01-05-libksba-1.6.3.md
  dev-libs/libksba/Manifest
  dev-libs/libksba/libksba-1.6.3.ebuild
Labels: alpha, beta, main, flatcar-3446

#398 sys-apps/portage: Move from coreos-overlay and update
  .github/workflows/packages-list
  changelog/updates/2022-12-12-portage-update.md
  sys-apps/file/Manifest
  sys-apps/file/file-5.43-r2.ebuild
  sys-apps/file/file-5.44-r1.ebuild
  sys-apps/file/file-9999.ebuild
  sys-apps/file/files/file-5.39-portage-sandbox.patch
  sys-apps/file/files/file-5.40-revert-char-count.patch
  sys-apps/file/files/file-5.40-seccomp-faccessat.patch
  sys-apps/file/files/file-5.40-seccomp-fstatat64.patch
  sys-apps/file/files/file-5.40-xz_magic.patch
  sys-apps/file/files/file-5.43-configure-clang16.patch
  sys-apps/file/files/file-5.43-portage-sandbox.patch
  sys-apps/file/files/file-5.43-seccomp-fstatat64-musl.patch
  sys-apps/file/files/file-5.44-limits-solaris.patch
  sys-apps/file/files/file-5.44-seccomp-utimes.patch
  sys-apps/file/metadata.xml
  sys-apps/portage/Manifest
  sys-apps/portage/files/README.RESCUE
  sys-apps/portage/files/portage-3.0.38.1-xz-32-bit.patch
  sys-apps/portage/files/portage-ccache.conf
  sys-apps/portage/files/portage-tmpdir.conf
  sys-apps/portage/metadata.xml
  sys-apps/portage/portage-3.0.38.1-r6.ebuild
  sys-apps/portage/portage-3.0.41-r2.ebuild
  sys-apps/portage/portage-3.0.42-r1.ebuild
  sys-apps/portage/portage-3.0.43.ebuild
  sys-apps/portage/portage-9999.ebuild
  sys-libs/libseccomp/Manifest
  sys-libs/libseccomp/files/libseccomp-2.6.0-python-shared.patch
  sys-libs/libseccomp/libseccomp-2.5.1.ebuild
  sys-libs/libseccomp/libseccomp-2.5.2.ebuild
  sys-libs/libseccomp/libseccomp-2.5.4-r1.ebuild
  sys-libs/libseccomp/libseccomp-2.5.4.ebuild
  sys-libs/libseccomp/libseccomp-9999.ebuild
  sys-libs/libseccomp/metadata.xml
Labels: main

#406 dev-vcs/git: update to 2.37.5 for flatcar-3374
  changelog/security/2023-01-18-git-2.37.5.md
  changelog/updates/2022-01-18-git-2.37.5.md
  dev-vcs/git/Manifest
  dev-vcs/git/files/git-2.31.0_rc0-optional-cvs.patch
  dev-vcs/git/files/git-2.32.0-r1-test-t5582.patch
  dev-vcs/git/files/git-2.33.0_rc0-optional-cvs.patch
  dev-vcs/git/files/git-2.37.2-darwin-prefix-gettext.patch
  dev-vcs/git/files/git-2.37.2-unsafe-directory.patch
  dev-vcs/git/files/git-daemon-r1.initd
  dev-vcs/git/git-2.32.0-r1.ebuild
  dev-vcs/git/git-2.33.1.ebuild
  dev-vcs/git/git-2.35.1.ebuild
  dev-vcs/git/git-2.35.2.ebuild
  dev-vcs/git/git-2.35.3.ebuild
  dev-vcs/git/git-2.36.0.ebuild
  dev-vcs/git/git-2.36.1.ebuild
  dev-vcs/git/git-2.37.0.ebuild
  dev-vcs/git/git-2.37.1.ebuild
  dev-vcs/git/git-2.37.4.ebuild
  dev-vcs/git/git-2.37.5.ebuild
  dev-vcs/git/git-9999-r1.ebuild
  dev-vcs/git/git-9999-r2.ebuild
  dev-vcs/git/git-9999-r3.ebuild
  dev-vcs/git/git-9999.ebuild
  dev-vcs/git/metadata.xml
Labels: stable, flatcar-3374

#407 dev-vcs/git: update to 2.37.5 for flatcar-3446
  changelog/security/2023-01-18-git-2.37.5.md
  changelog/updates/2022-01-18-git-2.37.5.md
  dev-vcs/git/Manifest
  dev-vcs/git/files/git-2.31.0-darwin-prefix-gettext.patch
  dev-vcs/git/files/git-2.33.0_rc0-optional-cvs.patch
  dev-vcs/git/git-2.35.1.ebuild
  dev-vcs/git/git-2.35.5.ebuild
  dev-vcs/git/git-2.37.3.ebuild
  dev-vcs/git/git-2.37.4.ebuild
  dev-vcs/git/git-2.37.5.ebuild
  dev-vcs/git/git-2.38.0.ebuild
  dev-vcs/git/git-2.38.1.ebuild
  dev-vcs/git/git-9999-r1.ebuild
  dev-vcs/git/git-9999-r2.ebuild
  dev-vcs/git/git-9999-r3.ebuild
  dev-vcs/git/git-9999.ebuild
Labels: beta, flatcar-3446
